
name: Building Uniblow binaries


on:
  #release:
  #  types: [created]
  push:
    branches: [ cicd ]


jobs:

  # build_win:

    # runs-on: windows-2019

    # steps:
    # - uses: actions/checkout@v2
    # - name: Set up Python
      # uses: actions/setup-python@v2
      # with:
        # python-version: '3.8'
        # architecture: 'x64'
    # - name: Insert Infura key
      # env:
        # INFURA_APIKEY: ${{ secrets.INFURA_APIKEY }}
      # run: |
        # (Get-Content wallets\ETHwallet.py) -Replace '"xxx" # Put your Infura key here', ('"' + $Env:INFURA_APIKEY +'"') | Set-Content wallets\ETHwallet.py
    # - name: Build bin package
      # run: |
        # cd package
        # ./Build-Windows.bat
    # - name: 'Archive windows bin (unsigned!)'
      # uses: actions/upload-artifact@v2
      # with:
        # name: windist
        # path: |
          # dist/


  build_linux:

    container: node:14.16

    steps:
    - name: Insert Infura key
      env:
        INFURA_APIKEY: ${{ secrets.INFURA_APIKEY }}
      run: |
        sed -i 's/"xxx" # Put your Infura key here/'"$INFURA_APIKEY"'/g' wallets\ETHwallet.py
    - name: Prepare Debian system
      run: |
        sudo apt update
        sudo apt install -y libsdl2-2.0-0 python3-venv python3-pip python3-pyscard
    - name: Build bin package
      run: |
        bash package/Build-Debian.sh
    - name: 'Archive linux bin (unsigned!)'
      uses: actions/upload-artifact@v2
      with:
        name: nuxdist
        path: |
          dist/
